### PR TITLE
Fix #19 — Add archiving customization howto

### LINKED ISSUE #19: How to: archive mails without attachments
Continuation of https://github.com/sympa-community/sympa/issues/303

You need to override `default/mhonarc-ressources.tt2` and set [`MIMEINCS`](https://www.mhonarc.org/MHonArc/doc/resources/mimeincs.html) or [`MIMEEXCS`](https://www.mhonarc.org/MHonArc/doc/resources/mimeexcs.html) in it.

Todo:
- [x] test
- [x] include in documentation

### PR DESCRIPTION
**Pull request by ldidry**

### CODE REVIEW

**Comment by ikedas** [comment]
I feel this article would be better to linked from "[Customizing Sympa services](https://github.com/sympa-community/sympa-community.github.io/blob/master/manual/customize.md#customizing-sympa-services)" - "Archives".

**Comment by ldidry** [comment]
Ok. I'll change its place.

**Comment by ikedas** [comment]
I created [`customize/archives.md`](https://github.com/sympa-community/sympa-community.github.io/blob/master/manual/customize/archives.md) (I don't know why but I forgot to import it from old site).  @ldidry, you may add your content to this page or may create a new page.

**Comment by ldidry** [comment]
I moved my example in `customize/archives.md`.

**Pull request merged**
