### PR TITLE
Remove empty section "Upgrading from Sympa prior to 5.0"

### PR DESCRIPTION
**Pull request by racke**

### CODE REVIEW

**Comment by ikedas** [comment]
I don't think it should be removed.

**Comment by racke** [comment]
Please state the reason why you would not remove an empty section about upgrade from a version released decades ago.

**Comment by ikedas** [comment]
> Please state the reason why you would not remove an empty section about upgrade from a version released decades ago.

UNESCO has been running Sympa 3.x until just a few years ago (Now they are [running 6.2.24](https://lists.unesco.org/wws/), though).  It is not so impossible that some sites are still running 5.0 or earlier.
Anyways I think a better solution is adding more contents instead of limiting information.

**Comment by racke** [comment]
There is currently no information, just an empty section. Anyway, that's my last two cents on this matter. Please either close or merge this PR.

**Pull request closed without merging**
