### PR TITLE
Note on wwsympa.service username

### PR DESCRIPTION
**Pull request by dverdin**
Added a note to warn that wwsympa.service will need to be customized.

### CODE REVIEW

**Comment by ikedas** [comment]
Hi @dverdin,
Ouch, example files are outdated. We should replace it with those generated by source distribution.

Besides, user name may be customized by adding this line in `/etc/sysconfig/sympa`:
```
FCGI_OPTS="-M 0600 -U apache"
```
(Note that new service files: Current examples won't work correctly).

**Comment by dverdin** [comment]
Yes, I noticed: we started using it for Universalistes. Actually, we didn't have that much to change to make them work.
As we have now a working instance using this setup, I'll update the documentation accordingly to your remarks and my own experience in the current PR. Agreed?

**Comment by ikedas** [comment]
Agreed. Thanks!

I realized that example need not contained in documentation: It is bundled in binary distribution (if it supports), or generated by source distribution.

---
BTW if you submit a PR in the next time, could you please create a branch on your fork instead of master repo?

**Comment by dverdin** [comment]
> BTW if you submit a PR in the next time, could you please create a branch on your fork instead of master repo?

Oh yes. I edited the file from master repo instead of a fork of mine.
Will do next time. Cheers!

**Comment by dverdin** [comment]
OK. I think it's OK now. What do you think?

**Pull request merged**
